### ISSUE TITLE
Events are returned without signup_start and end signup_end

### ISSUE THREAD

**Issue by PelicanQ** [fsek/WebWebWeb#11]
Call `GET /events` and see that events are missing `signup_start` and `signup_end`.

Make it so these are included in the response

Only one file needs to be edited.

Create a branch of main and submit pull request. 

You can mention this issue in your PR by writing #11 in the comment in your PR.

**Comment by Equasa** [comment]
är denna inte redan implementerad?

**Comment by PelicanQ** [comment]
Nää det saknas två fält för schemat. Är en mindre issue tänkt för nya till backenden :)

**Comment by PelicanQ** [comment]
Reopening, since it's not fixed. Let's leave this as a stepping stone/first issue for someone else to do.

**Comment by Kurtthecat** [comment]
seems to have been fixed!
