### ISSUE TITLE
Songs! (Routes)

### ISSUE THREAD

**Issue by PelicanQ** [fsek/WebWebWeb#16]
- Create a `song_router` with routes for: 
  - viewing all songs 
  - viewing one song
  - adding a song
  - deleting a song
  - editing a song
- You'll need a few Pydantic schemas for these routes. You can use the constant for max lengths of title/lyrics in the Create schema. This is nice API design because then if a client sends a too long title, they wont recieve `Internal Server Error` from us trying to insert a too long title. Instead FastAPI will see that our Create schema demands a title no longer than X characters. So FastAPI will stop and return a 400 type error (`Bad Request`) with a helpful note that title was too long.
- Dont forget permissions. You'll have to add another string into `PERMISSION_TARGET`.

**Comment by Snowald** [comment]
A song in the database should contain these fields

  int? id;
  String? title;
  String? author;
  String? melody;
  String? content;
