### ISSUE TITLE
Create cafe shift

### ISSUE THREAD

**Issue by rfvcft** [fsek/WebWebWeb#39]
- Create a db model for cafe_shift
  - It should have a start time and a end time (as datetime fields)
  - It should have a cafe worker (of type CafeWorker, see other issue)
  - It should have a field which checks if it is the current user who is the one who is signed up to the shift (boolean)
- Create a `cafe_shift_router` with routes for:
  - Viewing all cafe shifts
  - Viewing a single cafe shift
  - Viewing all shifts between two dates
  - Adding a cafe shift
  - Removing a cafe shift
  - Editing a cafe shift
 - Add corresponding Pydantic schemas for the routes. 
 - Don't forget permissions. You will have to add another string into the `PERMISSION_TARGET` array
 - Added bonus if you add seeding for cafe shifts! (seeding is filling the db with some test data in dev. It's done in seed.py)

**Comment by OlleSettergren** [comment]
I've started implementing this (and the cafe_worker model). Can't add myself as an assignee though?
